# Database Parameters
quarkus.datasource."store.purchases".db-kind=postgresql
quarkus.datasource."store.purchases".reactive.url=postgresql://${DB_HOST}:${DB_PORT}/${STORE_PURCHASE_DB}
#quarkus.datasource.db-kind=${SYGEMAL_DB_KIND:postgresql}
quarkus.datasource."store.purchases".username=${STORE_PURCHASE_USER}
quarkus.datasource."store.purchases".password=${STORE_PURCHASE_PASSWORD}
quarkus.datasource."store.purchases".reactive.max-size=${DB_POOL_MAX_SIZE:10}
quarkus.datasource."store.purchases".reactive.idle-timeout=${DB_POOL_IDLE_TIMEOUT:100ms}
quarkus.datasource."store.purchases".reactive.max-lifetime=${DB_POOL_MAX_LIFETIME:120s}
quarkus.datasource."store.purchases".reactive.reconnect-attempts=${DB_POOL_RECONNECT_ATTEMPTS:3}
quarkus.datasource."store.purchases".reactive.cache-prepared-statements=${DB_POOL_CACHE_PREPARED_STATEMENTS:true}
#quarkus.datasource.jdbc=false
#quarkus.hibernate-orm.datasource=<default>
quarkus.hibernate-orm."store.purchases".schema-management.strategy=none
quarkus.hibernate-orm."store.purchases".log.sql=true
quarkus.hibernate-orm."store.purchases".dialect=org.hibernate.dialect.PostgreSQLDialect
quarkus.hibernate-orm."store.purchases".validate-in-dev-mode=false
quarkus.hibernate-orm."store.purchases".datasource=store.purchases
quarkus.hibernate-orm."store.purchases".packages=store.purchase.infrastructure.persistence.entity,io.quarkus.hibernate.reactive.panache

# JDBC (migrations Flyway)
quarkus.datasource."store.purchases".jdbc.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${STORE_PURCHASE_DB}
quarkus.flyway."store.purchases".migrate-at-start=true
quarkus.flyway."store.purchases".locations=db/migration/purchases

# App Store verification
store.purchase.app-store.environment=${STORE_PURCHASE_APP_STORE_ENVIRONMENT:SANDBOX}
store.purchase.app-store.enable-online-checks=${STORE_PURCHASE_APP_STORE_ENABLE_ONLINE_CHECKS:false}
store.purchase.app-store.enable-api-lookup=${STORE_PURCHASE_APP_STORE_ENABLE_API_LOOKUP:true}
store.purchase.app-store.issuer-id=${STORE_PURCHASE_APP_STORE_ISSUER_ID}
store.purchase.app-store.key-id=${STORE_PURCHASE_APP_STORE_KEY_ID}
store.purchase.app-store.private-key-path=${STORE_PURCHASE_APP_STORE_PRIVATE_KEY_PATH}
store.purchase.app-store.paths=${STORE_PURCHASE_APP_STORE_CERTS_PATH}

# Google API Client Configuration
google.server.app=${GOOGLE_CLIENT_SERVER_APP_NAME}
google.client.developerKey=${GOOGLE_CLIENT_DEVELOPER_KEY}
google.client.clientSecret=${GOOGLE_CLIENT_SECRET:}
google.client.clientId=${GOOGLE_CLIENT_ID:}
google.client.refreshToken=${GOOGLE_REFRESH_TOKEN:}
google.client.accessToken=${GOOGLE_ACCESS_TOKEN:}

# Path to the service account JSON file
# Option A: From Classpath (if in src/main/resources/)
# google.client.serviceAccountPath=service-account-google-play.json
# Option B: From File System (use "file:" prefix for clarity, or just the path)
google.client.serviceAccountPath=${GOOGLE_SERVICE_ACCOUNT_PATH:}

# If you need to specify scopes:
google.client.scopes=${GOOGLE_CLIENT_SCOPES}

# Optional:quarkus-oidc Redirect URI
# google.client.redirectUri=http://127.0.0.1:8000/api
google.oidc.audience=${GOOGLE_CLIENT_AUDIENCE}
