# Database Parameters
quarkus.datasource."account".db-kind=postgresql
quarkus.datasource."account".reactive.url=postgresql://${DB_HOST}:${DB_PORT}/${ACCOUNT_DB}
quarkus.datasource."account".username=${ACCOUNT_USER}
quarkus.datasource."account".password=${ACCOUNT_PASSWORD}
quarkus.datasource."account".reactive.max-size=${DB_POOL_MAX_SIZE:10}
quarkus.datasource."account".reactive.idle-timeout=${DB_POOL_IDLE_TIMEOUT:100ms}
quarkus.datasource."account".reactive.max-lifetime=${DB_POOL_MAX_LIFETIME:120s}
quarkus.datasource."account".reactive.reconnect-attempts=${DB_POOL_RECONNECT_ATTEMPTS:3}
quarkus.datasource."account".reactive.cache-prepared-statements=${DB_POOL_CACHE_PREPARED_STATEMENTS:true}
#quarkus.datasource.jdbc=false
#quarkus.hibernate-orm.datasource=<default>
quarkus.hibernate-orm."account".schema-management.strategy=none
quarkus.hibernate-orm."account".log.sql=true
quarkus.hibernate-orm."account".dialect=org.hibernate.dialect.PostgreSQLDialect
quarkus.hibernate-orm."account".validate-in-dev-mode=false

quarkus.hibernate-orm."account".datasource=account
quarkus.hibernate-orm."account".packages=account.infrastructure.persistence.entity,io.quarkus.hibernate.reactive.panache

quarkus.datasource."account".jdbc.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${ACCOUNT_DB}
quarkus.flyway."account".migrate-at-start=true
quarkus.flyway."account".locations=db/migration/account


# Hôte SMTP
quarkus.mailer."account".host=${ACCOUNT_MAIL_HOST:smtp.gmail.com}
# Port
quarkus.mailer."account".port=${ACCOUNT_MAIL_PORT}
# Authentification
quarkus.mailer."account".username=${ACCOUNT_MAIL_USER}
quarkus.mailer."account".password=${ACCOUNT_MAIL_PASSWORD}
# Sécurité
quarkus.mailer."account".start-tls=REQUIRED
quarkus.mailer."account".tls=false
%dev.quarkus.mailer."account".mock=true
# Timeout
#quarkus.mailer.connection-timeout=10s
quarkus.mailer."account".timeout=60s
# Expéditeur par défaut
quarkus.mailer."account".from=${ACCOUNT_MAIL_FROM}
account.email.validation-url=${ACCOUNT_EMAIL_VALIDATION_URL:http://localhost:8080/account/verify-email}
