#!/usr/bin/env bash
set -e

echo "🚀 Initialisation des bases avec variables .env..."

psql -v ON_ERROR_STOP=1 \
  --username postgres \
  --dbname postgres <<EOSQL

-- ==========================================
-- LIFE PING DATABASE
-- ==========================================

CREATE DATABASE ${LIFE_PING_DB};

CREATE USER ${LIFE_PING_USER}
  WITH ENCRYPTED PASSWORD '${LIFE_PING_PASSWORD}'
  NOSUPERUSER NOCREATEDB NOCREATEROLE;

GRANT CONNECT ON DATABASE ${LIFE_PING_DB} TO ${LIFE_PING_USER};

\connect ${LIFE_PING_DB}

GRANT USAGE, CREATE ON SCHEMA public TO ${LIFE_PING_USER};

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${LIFE_PING_USER};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${LIFE_PING_USER};
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO ${LIFE_PING_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT ALL ON TABLES TO ${LIFE_PING_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT ALL ON SEQUENCES TO ${LIFE_PING_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT ALL ON FUNCTIONS TO ${LIFE_PING_USER};

-- ==========================================
-- BUSINESS CARD DATABASE
-- ==========================================

\connect postgres

CREATE DATABASE ${BUSINESS_CARD_DB};

CREATE USER ${BUSINESS_CARD_USER}
  WITH ENCRYPTED PASSWORD '${BUSINESS_CARD_PASSWORD}'
  NOSUPERUSER NOCREATEDB NOCREATEROLE;

GRANT CONNECT ON DATABASE ${BUSINESS_CARD_DB} TO ${BUSINESS_CARD_USER};

\connect ${BUSINESS_CARD_DB}

GRANT USAGE, CREATE ON SCHEMA public TO ${BUSINESS_CARD_USER};

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${BUSINESS_CARD_USER};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${BUSINESS_CARD_USER};
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO ${BUSINESS_CARD_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT ALL ON TABLES TO ${BUSINESS_CARD_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT ALL ON SEQUENCES TO ${BUSINESS_CARD_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT ALL ON FUNCTIONS TO ${BUSINESS_CARD_USER};

EOSQL