package account.domain.model;

public enum TokenType {
    EMAIL_VERIFICATION_CODE,
    EMAIL_VERIFICATION_LINK,
    PASSWORD_RESET_CODE,
    PASSWORD_RESET_LINK,
    SESSION_REFRESH,
    VERIFY_CODE,
    VERIFY_TOKEN,
    REFRESH_TOKEN
}
