-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgQJ0b7Hyt1EUKmlsq
HfD7OGeHo/KV9BEzuWL4IRps/8CgCgYIKoZIzj0DAQehRANCAASYhI8AlX5GHqk4
MjOr8QwtRR5GQyHXj3PUx47zfIYNiTXtteVyHmGIS3djnghqUBaKJLOUZE7CXl6c
wh8beiZ+
-----END PRIVATE KEY-----